limits_config:
  # Whether or not old samples will be rejected.
  # CLI flag: -validation.reject-old-samples
  reject_old_samples: false

  # Maximum accepted sample age before rejecting.
  # CLI flag: -validation.reject-old-samples.max-age
  #  [reject_old_samples_max_age: <duration> | default = 1w]
  reject_old_samples_max_age: 43800h

  max_query_length: 43800h

auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
    - from: 2020-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks

block_builder:
    # The maximum duration of a timeseries chunk in memory. If a timeseries runs
    # for longer than this, the current chunk will be flushed to the store and a
    # new chunk created.
    # CLI flag: -blockbuilder.max-chunk-age
    max_chunk_age: 43800h
