{
 "title": "Health",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "beat/min" } },
   "targets": [
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"resting_heart_rate\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    },
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"heart_rate\") \n  |> filter(fn: (r) => r._field == \"avg\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    },
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"walking_heart_rate_average\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    },
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"heart_rate\") \n  |> filter(fn: (r) => r._field == \"min\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    },
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"heart_rate\") \n  |> filter(fn: (r) => r._field == \"max\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    }
   ]
  },
  {
   "title": "Daily Step Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "step/day" } },
   "targets": [
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"step_count\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    },
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"walking_running_distance\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    }
   ]
  },
  {
   "title": "Walking Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"walking_speed\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    }
   ]
  },
  {
   "title": "Walking Double Support",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"walking_double_support_percentage\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    }
   ]
  },
  {
   "title": "Daily Physical Effort",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kcal/hr·kg" } },
   "targets": [
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"physical_effort\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    },
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"active_energy\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    }
   ]
  },
  {
   "title": "Walking Step Length",
   "type": "timeseries",
   "description": "Distance between two steps.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "targets": [
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"walking_step_length\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    }
   ]
  },
  {
   "title": "Stand Hours / Workout Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"apple_stand_hour\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    },
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"apple_exercise_time\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({r with _value: r._value / 60.0}))\n  |> yield(name: \"mean_qty\")\n"
    }
   ]
  },
  {
   "title": "Stair Speed",
   "type": "timeseries",
   "description": "Climbing speed in stairs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"stair_speed_up\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    },
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"stair_speed_down\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    }
   ]
  },
  {
   "title": "Respiratory rate",
   "type": "timeseries",
   "description": "Breaths per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "count/min" } },
   "targets": [
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"respiratory_rate\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    }
   ]
  },
  {
   "title": "Time in Daylight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"time_in_daylight\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    }
   ]
  },
  {
   "title": "Blood Oxygen Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"blood_oxygen_saturation\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    }
   ]
  },
  {
   "title": "VO2Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ml/(kg·min)" } },
   "targets": [
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"vo2_max\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    }
   ]
  },
  {
   "title": "Heart Rate Variability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"apple\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"heart_rate_variability\") \n  |> filter(fn: (r) => r._field == \"qty\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean_qty\")\n"
    }
   ]
  }
 ]
}