// Code generated by oapi-gen. DO NOT EDIT.

package api

// Docs returns a set of property descriptions per property.
func (Point) Docs() map[string]string {
	return map[string]string{
		"source": "Source of the device that produced the data.",
	}
}
